name: Docker CI/CD
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      # - name: Lint frontend with ESLint
      #   working-directory: frontend
      #   run: npm run lint

      # - name: Build frontend Docker image
      #   working-directory: frontend
      #   run: docker build -t chatbot-frontend:test .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: backend
        run: |
          python -m pytest tests/

      - name: Lint with Ruff
        working-directory: backend
        run: |
          pip install ruff
          ruff check .

      # - name: Build backend Docker image
      #   # working-directory: backend
      #   # run: docker build -t chatbot-backend:test .
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: pottasaichaitanya/frontend-app:latest
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: pottasaichaitanya/backend-app:latest


      
